Set createRewards function
Explore-Beyond-Innovations/ZeroCheck_Contracts pull request #24
Opened 2024-12-20 07:13 UTC by Holamite

Set createRewards function: FIXES: https://github.com/Explore-Beyond-Innovations/ZeroCheck_Contracts/issues/9
## Fixes
- I implemented two functions for createNFTReward and createTokenReward
- I made sure all the test cases passed
- I also added some getter function to the code

2024-12-20 09:06 UTC, Ugo-X requested changes
We already have a token reward contract
You're not implementing it.
Take a look at this PR: https://github.com/Explore-Beyond-Innovations/ZeroCheck_Contracts/pull/22


and this one: https://github.com/Explore-Beyond-Innovations/ZeroCheck_Contracts/pull/14

2024-12-20 12:04 UTC, Holamite commented
##The Implementation
- I created a unified reward system that handles both NFTs and tokens Includes important state variables:

- References to both factory contracts
-A struct to track reward details
- A mapping to store rewards by event ID


The createReward function:

- I Creates an NFT contract through the NFT factory and sets up token rewards through the reward manager if specified stores all reward information in the mapping.

2024-12-20 12:55 UTC, Ugo-X commented
also run forge fmt before pushing

2024-12-21 20:35 UTC, Ugo-X requested changes
You should move the create nft reward inside the rewardmanager contract.

And make two functions.

1. createTokenReward for creating token rewards and store the token address in the reward mapping
2. createNftRealwards for creating NFT token rewards (this one calls the NFTFactory to deploy the NFT and then he should store the nft address in the reward mapping

making them two separate functions, which can be handled from the frontend.

2025-01-20 13:50 UTC, Ugo-X approved these changes

2025-01-20 13:53 UTC, merged